### ISSUE TITLE
Row edit icons come over text...

### ISSUE THREAD

**Issue by shramee** [pootlepress/ppb-live-editor#22]
Add some padding above rows to make some space for row edit icons.

**Comment by jamiemarsland** [comment]
At the moment there is too much movement when working as the rows jump with the nice animation. How about we only animate when a user hovers over the row sorting icon?

**Comment by jamiemarsland** [comment]
Needs discussion..the reason to do this was so that users could edit the H2 that we put in. But at the moment they still can't do that easliy because as soon as they move cursor down the icons cover the text. Let's discuss.

See video - maybe we should put row icons to appear above the row ?

https://vimeo.com/152262683

**Comment by jamiemarsland** [comment]
This still isn't quite right. 

At the moment when you click into the text,  the row icons vanish so you can (which is good). However then the row icons vanish so you can't access them again. I don;t think this is very user friendly. I really like the idea of the icons moving up like we had before, but we just the user to be able to click into the first heading a be able to type without the icons moving back down. 

Here's a video of the problem

https://vimeo.com/152799287
